variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_DEPTH: "3"
  CCACHE_BASEDIR: "${CI_PROJECT_DIR}"
  CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"

cache:
  paths:
    - ccache

.robotpkg-pinocchio: &robotpkg-pinocchio
  except:
    - gh-pages
  before_script:
    - mkdir -p ccache
  script:
    - cd /root/robotpkg/math/pinocchio
    - git pull
    - make checkout MASTER_REPOSITORY="dir ${CI_PROJECT_DIR}"
    - make install
    - cd work.$(hostname)/$(make show-var VARNAME=DISTNAME)
    - make check
    - make doc
    - mv doc/doxygen-html ${CI_PROJECT_DIR}


robotpkg-pinocchio-14.04:
  <<: *robotpkg-pinocchio
  image: eur0c.laas.fr:5000/stack-of-tasks/pinocchio/pinocchio:14.04

robotpkg-pinocchio-dubnium:
  <<: *robotpkg-pinocchio
  image: eur0c.laas.fr:5000/stack-of-tasks/pinocchio/pinocchio:dubnium

robotpkg-pinocchio-16.04:
  <<: *robotpkg-pinocchio
  image: eur0c.laas.fr:5000/stack-of-tasks/pinocchio/pinocchio:16.04
  artifacts:
    expire_in: 1 day
    paths:
      - doxygen-html/

robotpkg-pinocchio-18.04:
  <<: *robotpkg-pinocchio
  image: eur0c.laas.fr:5000/stack-of-tasks/pinocchio/pinocchio:18.04


.robotpkg-py-pinocchio: &robotpkg-py-pinocchio
  except:
    - gh-pages
  before_script:
    - mkdir -p ccache
  script:
    - cd /root/robotpkg/math/py-pinocchio
    - git pull
    - make checkout MASTER_REPOSITORY="dir ${CI_PROJECT_DIR}"
    - make install
    - cd work.$(hostname)/$(make show-var VARNAME=DISTNAME)
    - make check
    - make doc
    - mv doc/doxygen-html ${CI_PROJECT_DIR}


robotpkg-py-pinocchio-14.04:
  <<: *robotpkg-py-pinocchio
  image: eur0c.laas.fr:5000/stack-of-tasks/pinocchio/py-pinocchio:14.04

robotpkg-py-pinocchio-dubnium:
  <<: *robotpkg-py-pinocchio
  image: eur0c.laas.fr:5000/stack-of-tasks/pinocchio/py-pinocchio:dubnium

robotpkg-py-pinocchio-16.04:
  <<: *robotpkg-py-pinocchio
  image: eur0c.laas.fr:5000/stack-of-tasks/pinocchio/py-pinocchio:16.04
  artifacts:
    expire_in: 1 day
    paths:
      - doxygen-html/

robotpkg-py-pinocchio-18.04:
  <<: *robotpkg-py-pinocchio
  image: eur0c.laas.fr:5000/stack-of-tasks/pinocchio/py-pinocchio:18.04

robotpkg-py-pinocchio-py3-14.04:
  <<: *robotpkg-py-pinocchio
  image: eur0c.laas.fr:5000/stack-of-tasks/pinocchio/py-pinocchio-py3:14.04

robotpkg-py-pinocchio-py3-dubnium:
  <<: *robotpkg-py-pinocchio
  image: eur0c.laas.fr:5000/stack-of-tasks/pinocchio/py-pinocchio-py3:dubnium

robotpkg-py-pinocchio-py3-16.04:
  <<: *robotpkg-py-pinocchio
  image: eur0c.laas.fr:5000/stack-of-tasks/pinocchio/py-pinocchio-py3:16.04

robotpkg-py-pinocchio-py3-18.04:
  <<: *robotpkg-py-pinocchio
  image: eur0c.laas.fr:5000/stack-of-tasks/pinocchio/py-pinocchio-py3:18.04




