language: python
python:
- "2.7"
sudo: required
compiler:
- gcc
# - clang
env:
  global:
    - secure: "SnIBG/xLIHX3CSvUbqqsX8xTVqIqQ7fFS6HWO6KZQVBsT6yugTwYHbyhNiU531JejYJ/I3ZrDhXfYH3qFZiYxnH1sifvwV+fnTtMXpPN7qPZwIymkjcmm6gJF51e0C7VOfUbvKFv0ngwj+ul21rgZSMuoEvxPK0WxtE3/ZSfn9c="
    - APT_DEPENDENCIES="doxygen libeigen3-dev "
    - DEBSIGN_KEYID=5AE5CD75
    - LCOV_IGNORE_RULES="*unittest* /opt/openrobots/*"
  matrix:
    # - BUILDTYPE=Release
    # - BUILDTYPE=Debug
    - BUILDTYPE=Minsizerel
notifications:
email:
- hpp-source@laas.fr
branches:
only:
- master
- debian
- devel
matrix:
allow_failures:
- compiler:
script:
  - export CMAKE_ADDITIONAL_OPTIONS="-DCMAKE_BUILD_TYPE=${BUILDTYPE}"
  - sudo free -m -t
  - travis_wait ./.travis/run ../travis_custom/custom_build
  - export PYTHONPATH=/tmp/_ci/install/lib/python2.7/site-packages
  - python ./python/bindings.py
  - python ./python/test_model.py
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
before_install: ./travis_custom/custom_before_install
