title: Pinocchio
description: Fast Forward Inverse Dynamic for Multibody Systems
baseurl: "/pinocchio"
github-url: "https://github.com/stack-of-tasks/pinocchio"
remote_theme: Gepetto/jekyll-theme
markdown: kramdown

category_list:
  - name: Getting Started
    icon: graduation-cap
    links:
      - name: Tutorials
        url: http://projects.laas.fr/gepetto/doc/stack-of-tasks/pinocchio/master/md_doc_d-labs_1-directgeom.html
  - name: Documentation
    icon: book
    links:
      - name: Doxygen
        url: http://projects.laas.fr/gepetto/doc/stack-of-tasks/pinocchio/master/
  - name: Development
    icon: wrench
    links:
      - name: View on Github
        url: http://www.github.com/stack-of-tasks/pinocchio
  - name: Support
    icon: question-circle
